### PR TITLE
Add forge branch

### PR DESCRIPTION
**Pull request by tmvkrpxl0**
Some of changes made to groovy build script is not applied because Forge requires every mod to have valid main class and mods.toml. PR of Forge branch for Toolbox and Transporter will be uploaded soon
This PR isn't able to be merged, as it's for new branch

### CODE REVIEW

**Comment by The-PPWD** [comment]
While I'm not familiar with Forge at all and some of my problems may come from that inexperience, I have encountered some errors with this branch that should be resolved before merging.

1. When running any of the `run*` (runClient, etc.) tasks from IntelliJ, it errors with `Invalid module name: '' is not a Java identifier`.
2. When running any of the `run*` (runClient, etc.) tasks from Gradle, it errors with `Invalid paths argument, contained no existing paths: [D:\Programs\Rayon\build\resources\testmod, D:\Programs\Rayon\build\classes\java\testmod]`. (Paths may be different on your system.)
3. When building the jars and running them in a standalone instance of Forge, various errors occur depending on which jars are present (rayon, rayon-core, etc.). If you want the specific errors for the specific jars I can provide them, though I would imagine that they are reproducible.

There are some other things that can be cleaned up/changed as well (like jar-in-jar/shadow) but they can be delayed for future commits and aren't crucial for it to run like these are.

If there's something obvious that I've done wrong here please let me know as I don't understand Forge and it's toolchain. If you can't reproduce some of these errors, I'd recommend clearing any caches you have as I started with a fresh clone.

**Comment by tmvkrpxl0** [comment]
I forgot to mention that, You need to publish forge branch of Transporter and Toolbox into maven local repo first. Their version and name is same as original one, so you might need to disable Lazurite maven repository so that It will get it from local. Sorry about that.
There was problem it not being able to find Toolbox and Transporter because of their name not being archives base name. but it is resolved now

**Comment by tmvkrpxl0** [comment]
> While I'm not familiar with Forge at all and some of my problems may come from that inexperience, I have encountered some errors with this branch that should be resolved before merging.
> 
> 1. When running any of the `run*` (runClient, etc.) tasks from IntelliJ, it errors with `Invalid module name: '' is not a Java identifier`.
> 2. When running any of the `run*` (runClient, etc.) tasks from Gradle, it errors with `Invalid paths argument, contained no existing paths: [D:\Programs\Rayon\build\resources\testmod, D:\Programs\Rayon\build\classes\java\testmod]`. (Paths may be different on your system.)
> 3. When building the jars and running them in a standalone instance of Forge, various errors occur depending on which jars are present (rayon, rayon-core, etc.). If you want the specific errors for the specific jars I can provide them, though I would imagine that they are reproducible.
> 
> There are some other things that can be cleaned up/changed as well (like jar-in-jar/shadow) but they can be delayed for future commits and aren't crucial for it to run like these are.
> 
> If there's something obvious that I've done wrong here please let me know as I don't understand Forge and it's toolchain. If you can't reproduce some of these errors, I'd recommend clearing any caches you have as I started with a fresh clone.

I haven't tried to build it and use it in minecraft though, I'll test them right now

**Comment by tmvkrpxl0** [comment]
Seems like there's problem with Mixin refmap, as it's not included on production

**Comment by tmvkrpxl0** [comment]
I've succeed running it with production jar. It seems like mixin doesn't behave nicely when using `shadowJar` instead of `build`. Solution was, using shadowed jar for rayon and using not shadowed jar for everything else(rayon_core, rayon_entity, toolbox, transporter).
I'm not sure what's causing this issue but currently, `shadowJar` does not include refmap into jar

**Comment by tmvkrpxl0** [comment]
Ok it should work now, I have faced same problem you faced after deleting Rayon project folder entirely and cloning it again.

**Pull request merged**
